# Generated by Django 3.2 on 2023-02-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_comment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.title', verbose_name='произведение'),
        ),
    ]
